const data = {
  projects: [
    {
      id: 1,
      name: 'AuxilloRX',
      slug: 'auxillorx',
      dp: '/img/auxillorx.jpg',
      type: 'site',
      images: ['/img/auxillorx.jpg'],
      mlink: 'https://auxillorx.com/',
      stacks: [
        'DART',
        'JAVASCRIPT',
        'NEST',
        'NODE',
        'AWS',
        'GIT',
        'FLUTTER',
        'FIGMA',
      ],
      rating: 4.0,
      description:
        'This app ensures easy access to medication information, reminders, and more.',
    },
    {
      id: 2,
      name: 'Swiftier',
      slug: 'swiftier-app',
      dp: '/img/swiftier.jpg',
      type: 'site',
      images: ['/img/swiftier.jpg'],
      mlink: 'https://swiftier.ca/',
      stacks: ['FLUTTER', 'DART', 'JAVA', 'ANDROID', 'IOS', 'API', 'FIGMA'],
      rating: 4.0,
      description:
        'With user-friendly features, competitive exchange rates, and robust security measures, this app simplifies international transactions.',
    },
    {
      id: 3,
      name: 'Kodex Site',
      slug: 'kodex-site',
      dp: '/img/kodex.jpg',
      type: 'site',
      images: ['/img/kodex.jpg'],
      mlink: 'https://kodexafrica.com/',
      stacks: [
        'HTML5',
        'CSS',
        'JAVASCRIPT',
        'PHP',
        'LARAVEL',
        'MySQL',
        'GIT',
        'LINUX',
      ],
      rating: 4.0,
      description:
        'A site for Kodex NG limited. Where I trained next gen on cutting-edge technologies.',
    },
    {
      id: 4,
      name: 'Aura',
      slug: 'aura',
      dp: '/img/aura01.jpg',
      type: 'site',
      images: ['/img/aura02.jpg', '/img/aura01.jpg'],
      mlink: 'https://apps.apple.com/ng/app/aura-by-transcorp-hotels/id6444285134',
      stacks: ['FLUTTER', 'DART', 'JAVA', 'ANDROID', 'IOS', 'APIs'],
      rating: 4.5,
      description: 'An online platform that helps you book accommodations.',
    },
    {
      id: 5,
      name: 'Blogshop',
      slug: 'blogshop',
      dp: '/img/blogshop01.PNG',
      type: 'site',
      images: ['/img/blogshop01.PNG'],
      mlink: 'https://www.blogshop.io',
      stacks: ['FLUTTER', 'DART', 'KOTLIN', 'ANDROID', 'IOS', 'JSON'],
      rating: 4.2,
      description: 'A storytelling app.',
    },
    {
      id: 6,
      name: 'QuickBill',
      slug: 'quickbill-app',
      dp: '/img/quickbill.jpg',
      type: 'site',
      images: ['/img/quickbill.jpg'],
      mlink: 'https://quickbillhq.com/',
      stacks: [
        'FLUTTER',
        'DART',
        'KOTLIN',
        'ANDROID',
        'IOS',
        'API',
        'FIGMA',
        'CROSS-PLATFORM',
      ],
      rating: 4.0,
      description:
        'Quickbill allows you to easily top-up airtime, pay for electricity, and manage educational fees all in one place.',
    },
  ],
};

export default data;
