const data = {
  projects: [
    {
      id: 1,
      name: 'AuxilloRX',
      slug: 'auxillorx',
      dp: '/img/auxillorx.jpg',
      type: 'site',
      images: ['/img/auxillorx.jpg'],
      mlink: 'https://auxillorx.com/',
      stacks: [
        'DART',
        'JAVASCRIPT',
        'NEST',
        'NODE',
        'AWS',
        'GIT',
        'FLUTTER',
        'FIGMA',
      ],
      rating: 4.0,
      description:
        'This app ensures easy access to medication information, reminders, and more.',
    },
    {
      id: 2,
      name: 'Swiftier',
      slug: 'swiftier-app',
      dp: '/img/swiftier.jpg',
      type: 'site',
      images: ['/img/swiftier.jpg'],
      mlink: 'https://swiftier.ca/',
      stacks: ['FLUTTER', 'DART', 'JAVA', 'ANDROID', 'IOS', 'API', 'FIGMA'],
      rating: 4.0,
      description:
        'With user-friendly features, competitive exchange rates, and robust security measures, this app simplifies international transactions.',
    },
    {
      id: 3,
      name: 'Kodex Site',
      slug: 'kodex-site',
      dp: '/img/kodex.jpg',
      type: 'site',
      images: ['/img/kodex.jpg'],
      mlink: 'https://kodexafrica.com/',
      stacks: [
        'HTML5',
        'CSS',
        'JAVASCRIPT',
        'PHP',
        'LARAVEL',
        'MySQL',
        'GIT',
        'LINUX',
      ],
      rating: 4.0,
      description:
        'A site for Kodex NG limited. Where I trained next gen on cutting-edge technologies.',
    },
    {
      id: 4,
      name: 'CBRecipe',
      slug: 'cb-recipe-app',
      dp: '/img/recipe.png',
      type: 'app',
      images: ['/img/recipe02.png', '/img/recipe01.png', '/img/recipe.png'],
      mlink: '/media/recipe.apk',
      stacks: ['FLUTTER', 'DART', 'JAVA', 'ANDROID', 'IOS', 'JSON'],
      rating: 4.0,
      description: 'A Recipe app.',
    },
    {
      id: 5,
      name: 'QuickBill',
      slug: 'quickbill-app',
      dp: '/img/quickbill.jpg',
      type: 'site',
      images: ['/img/quickbill.jpg'],
      mlink: 'https://quickbillhq.com/',
      stacks: [
        'FLUTTER',
        'DART',
        'JAVA',
        'ANDROID',
        'IOS',
        'API',
        'FIGMA',
        'CROSS-PLATFORM',
      ],
      rating: 4.0,
      description:
        'Quickbill allows you to easily top-up airtime, pay for electricity, and manage educational fees all in one place.',
    },
  ],
};

export default data;
