const data = {
  projects: [
    {
      id: 1,
      name: 'AuxilloRX',
      slug: 'auxillorx',
      dp: '/img/auxillorx.jpg',
      type: 'site',
      images: ['/img/auxillorx.jpg'],
      mlink: 'https://auxillorx.com/',
      stacks: [
        'DART',
        'JAVASCRIPT',
        'NEST',
        'NODE',
        'AWS',
        'GIT',
        'FLUTTER',
        'FIGMA',
      ],
      rating: 4.0,
      description: 'Led mobile development of a healthcare app providing medication information, prescription reminders, and patient management. Built cross-platform on Flutter and deployed to both the App Store and Google Play, meeting healthcare compliance standards.',
    },
    {
      id: 2,
      name: 'Swiftier',
      slug: 'swiftier-app',
      dp: '/img/swiftier.jpg',
      type: 'site',
      images: ['/img/swiftier.jpg'],
      mlink: 'https://swiftier.ca/',
      stacks: ['FLUTTER', 'DART', 'JAVA', 'ANDROID', 'IOS', 'API', 'FIGMA'],
      rating: 4.0,
      description: 'Contract Flutter engineer and team lead on an international money transfer platform serving users across borders. Implemented cross-border payment flows, real-time exchange rates, and enterprise-grade fraud detection and security measures.',
    },
    {
      id: 3,
      name: 'Kodex Site',
      slug: 'kodex-site',
      dp: '/img/kodex.jpg',
      type: 'site',
      images: ['/img/kodex.jpg'],
      mlink: 'https://kodexafrica.com/',
      stacks: [
        'HTML5',
        'CSS',
        'JAVASCRIPT',
        'PHP',
        'LARAVEL',
        'MySQL',
        'GIT',
        'LINUX',
      ],
      rating: 4.0,
      description: 'Built the company website for Kodex NG Ltd using Laravel, MySQL, and vanilla JavaScript. Kodex is a tech training institution where I also served as Flutter developer and technical tutor, training 100+ students in mobile development.',
    },
    {
      id: 4,
      name: 'Aura',
      slug: 'aura',
      dp: '/img/aura01.jpg',
      type: 'site',
      images: ['/img/aura02.jpg', '/img/aura01.jpg'],
      mlink: 'https://apps.apple.com/ng/app/aura-by-transcorp-hotels/id6444285134',
      stacks: ['FLUTTER', 'DART', 'JAVA', 'ANDROID', 'IOS', 'APIs'],
      rating: 4.5,
      description: 'Flutter-built hotel booking app for Transcorp Hotels, one of Nigeria\'s leading hospitality brands. Features property listings, room selection, check-in management, and seamless booking flows — live on the Apple App Store.',
    },
    {
      id: 5,
      name: 'Blogshop',
      slug: 'blogshop',
      dp: '/img/blogshop01.PNG',
      type: 'site',
      images: ['/img/blogshop01.PNG'],
      mlink: 'https://www.blogshop.io',
      stacks: ['FLUTTER', 'DART', 'KOTLIN', 'ANDROID', 'IOS', 'JSON'],
      rating: 4.2,
      description: 'A Flutter-built storytelling and content platform for writers and readers. Supports rich content creation, discovery, and community engagement across Android and iOS.',
    },
    {
      id: 6,
      name: 'QuickBill',
      slug: 'quickbill-app',
      dp: '/img/quickbill.jpg',
      type: 'site',
      images: ['/img/quickbill.jpg'],
      mlink: 'https://quickbillhq.com/',
      stacks: [
        'FLUTTER',
        'DART',
        'KOTLIN',
        'ANDROID',
        'IOS',
        'API',
        'FIGMA',
        'CROSS-PLATFORM',
      ],
      rating: 4.0,
      description: 'Project managed and led mobile development of this VTU and bills payment app. Users can top up airtime, pay electricity bills, and manage school fees — all in one place. Built with Flutter on both iOS and Android as part of the Nawe ecosystem.',
    },
  ],
  posts: [
    {
      title: 'Building Blogshop: Flutter, writers, and storytelling',
      description:
        'A behind-the-scenes look at how I built Blogshop with Flutter, clean content layouts, and a polished cross-platform experience.',
      date: 'April 2026',
      tag: 'Tech',
    },
    {
      title: 'From prototype to product: shipping mobile experiences',
      description:
        'Lessons from turning ideas into shipped apps, focusing on user feedback, reusable UI, and maintaining quality.',
      date: 'March 2026',
      tag: 'Product',
    },
  ],
};

export default data;
